#!/bin/sh
CMD="$(basename $0)" # must be less than 15 characters long
if xset q | grep --color=never -E "Caps Lock: +on"
then
    if ! ps --no-headers -C "$CMD" -o pid | grep -v $$
    then
        sleep 5 && notify-send --hint int:transient:1 -u critical -a notify-sleep Warning "CapsLock ON"
    fi
else
    ps --no-headers -C "$CMD" -o pid | grep -v $$ | xargs -r kill
fi
