#!/bin/sh
if [ -n "$1" ]
then
    SECONDS="$1"
else
    SECONDS=5
fi
CMD="$(basename $0)" # must be less than 15 characters long
if xset q | grep --color=never -E "Caps Lock: +on"
then
    if ! ps --no-headers -C "$CMD" -o pid | grep -v $$
    then
        sleep "$SECONDS" && notify-send --hint int:transient:1 -u critical -a notify-sleep Warning "CapsLock ON"
    fi
else
    ps --no-headers -C "$CMD" -o pid | grep -v $$ | xargs -r kill
fi
