#!/bin/sh
INTERACTIVE=false
ARGS=true
PATTERN=
process_args() {
    if [ -z "$PATTERN" ]
    then
        PATTERN="$1"
        INTERACTIVE=true
    else
        PATTERN="$PATTERN|$1"
    fi
}
while [ "$#" -gt 0 ]
do
    if $ARGS
    then
        case "$1" in
        (--)
            ARGS=false
            ;;
        (-i)
            INTERACTIVE=true
            ;;
        (*)
            process_args "$1"
            ;;
        esac
    else
        process_args "$1"
    fi
    shift
done

IFS='
'
for DEVICE in $(lsblk -psrno NAME,TYPE,MOUNTPOINT,HOTPLUG,FSTYPE,LABEL \
    | sed 's/\\x20/ /g' | grep -E "(part|disk)  1 [^ ].*($PATTERN)")
do
    if $INTERACTIVE
    then
        IFS=' '
        read -p "Mount $(echo "$DEVICE" | sed 's/part  1//') [Y/n]? " RESPONSE
        IFS='
'
        case $RESPONSE in
        [Nn]*)
            continue
            ;;
        esac
    fi
    OUTPUT="$(udisksctl mount -b "$(echo "$DEVICE" | cut -d' ' -f1)")"
    OUTPUT="${OUTPUT%.}"
    echo "$OUTPUT"
    DEV_PATH="/${OUTPUT##* at /}"
    if [ -n "$SUDO_UID" ] && [ "$(stat -c "%u" "$DEV_PATH")" -ne "$SUDO_UID" ]
    then
        NAME="$(basename "$DEV_PATH")"
        mkdir -p "$HOME/mnt/$NAME"
        if bindfs -u $SUDO_UID -g $SUDO_GID "$DEV_PATH" "$HOME/mnt/$NAME"
        then
            echo "Binded at $HOME/mnt/$NAME"
        else
            rmdir "$HOME/mnt/$NAME"
        fi
    fi
done
