#!/bin/bash
## grep -vxf <(echo "$b") <(echo "$a") # a - b
if [ -z $2 ]
then
    echo "usage: minus <main_file_list> <file_list_to_remove_from_main_file_list>"
    exit 1
fi
grep -Fvxf "$2" "$1"

# [ bash script
# if [ -z $2 ]
# then
#     echo "usage: minus <main_file_list> <file_list_to_remove_from_main_file_list>"
#     exit 1
# fi

# set -f
# IFS=$'\n'

# FILE=$(cat $1)
# for i in $(cat $2)
# do
#     FILE=$(echo "$FILE" | sed -e "0,/^$i$/{//d;}")
# done

# echo "$FILE"

# unset IFS
# set +f
# ]